esphome:
  name: "${name}"
  friendly_name: ld2410
  comment: ld2410
  name_add_mac_suffix: true
  platformio_options:
    board_build.f_flash: 40000000L
    board_build.flash_mode: dio
    board_build.flash_size: 4MB
    board_build.f_cpu: 80000000L

  on_boot:
  - priority: 900.0
    then:
      - lambda: |-
          id(radar_bluetooth).turn_off();

  project:
    name: "Myrenic.ld2410"
    version: "${version}"
  min_version: 2025.2.0

dashboard_import:
  package_import_url: github://myrenic/ld240/Integrations/ESPHome/ld2410.yaml
  import_full_config: false

ota:
  - platform: esphome
    id: ota_default

wifi:
  power_save_mode: none
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "ld2410 Hotspot"

packages:
  core: !include Core.yaml
